---
- name: Converge
  hosts: all
  tasks:
    - name: update apt cache
      apt:
        update_cache: true
      become: true
    - name: "Include keepalived"
      include_role:
        name: "keepalived"
