---
kubernetes_cni_calico_manifest_url: https://docs.projectcalico.org/manifests/calico.yaml
kubernetes_cni_calicoctl_version: v3.18.0
kubernetes_cni_calicoctl_checksum: sha256:7152bdda15c9fd2c4723004931def11989e20fa0884f4fc45ae8b61cc836cd19

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

kubernetes_zone: example.com

kubernetes_control_plane_endpoint_address: "kube-api.{{ kubernetes_zone }}"
kubernetes_control_plane_endpoint_port: 64443
kubernetes_control_plane_endpoint_vip: 192.168.1.50

kubernetes_advertise_address: "{{ ansible_all_ipv4_addresses[0] }}"

kubernetes_is_initial_controlplane: false
kubernetes_initial_controlplane_hostvar_key: controlplane01
kubernetes_node_fqdn: "{{ ansible_hostname }}.{{ kubernetes_zone }}"
kubernetes_is_controlplane: false

kubernetes_cni_certificate_entrust_not_after: "+365d"