---
# handlers file for crio
- name: reload systemd
  ansible.builtin.systemd:
    name: crio
    daemon_reload: true
  become: true

- name: create swapoff flag
  ansible.builtin.lineinfile:
    path: /etc/iac_flags/swapoff.flag
    line: delete this file to enable the Disable Swap task.
    create: true
  become: true

- name: create reset flag
  ansible.builtin.lineinfile:
    path: /etc/iac_flags/kubeadm_reset.flag
    line: delete this file to enable the Clear default kubeadm files task.
    create: true
  become: true
