---
dependency:
  name: galaxy
driver:
  name: vagrant
verifier:
  name: testinfra
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
platforms:
  - name: controlplane01
    groups:
      - controlplane
    box: geerlingguy/ubuntu2004
    box_version: 1.0.2
    memory: 2048
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 10.5.50.1
        auto_config: true
  - name: controlplane02
    groups:
      - controlplane
    box: geerlingguy/ubuntu2004
    box_version: 1.0.2
    memory: 2048
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 10.5.50.2
        auto_config: true
