---
- hosts: all
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true
  become: yes

- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived

- hosts:
    - initial_controlplane
  roles:
    - crio
    - kubernetes

# - hosts:
#     - additional_controlplane
#     - nodes
#   roles:
#     - crio
#     - kubernetes
