---
- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived

- hosts:
    - initial_controlplane
  roles:
    - crio
    - kubernetes

- hosts:
    - additional_controlplane
    - nodes
  serial: 1
  roles:
    - crio
    - kubernetes
