---
- hosts: all
  tasks:
    - name: Create Configuration Directories
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        state: directory
      loop: "{{ com.ryezone.node.directories }}"
      become: true

    - name: Create Configuration Files
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: root
        group: root
      loop: "{{ com.ryezone.node.conf_files }}"
      become: true

    # install and configure pre-requisites
    - name: Touch Files
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        mode: 644
      loop:
        - /etc/modules-load.d/crio.conf
        - /etc/sysctl.d/99-kubernetes-cri.conf
      become: true
    - name: crio.conf - Set Values
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/crio.conf
        line: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: yes
    - name: load modules
      community.general.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: true
    - name: 99-kubernetes-cri.conf - Set Values
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        sysctl_set: true
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
      become: true
    - name: add cri-o Package signing Keys
      ansible.builtin.apt_key:
        url: "{{ item.url }}"
        keyring: "{{ item.keyring }}"
        id: "{{ item.key_id }}"
        state: present
      loop:
        - url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ com.ryezone.platform.k8s.cri_o.os }}/Release.key"
          keyring: "/etc/apt/trusted.gpg.d/libcontainers.gpg"
          key_id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
        - url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ com.ryezone.platform.k8s.cri_o.version }}/{{ com.ryezone.platform.k8s.cri_o.os }}/Release.key"
          keyring: /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg
          key_id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
      become: true
    - name: Add cri-o Package Repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.path }}"
        state: present
      loop:
        - path: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable
          repo: "deb [arch=amd64] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ com.ryezone.platform.k8s.cri_o.os }}/ /"
        - path: "/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ com.ryezone.platform.k8s.cri_o.version }}"
          repo: "deb [arch=amd64] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ com.ryezone.platform.k8s.cri_o.version }}/{{ com.ryezone.platform.k8s.cri_o.os }}/ /"
      become: true

    # - name: Update Cache
    #   apt:
    #     cache_valid_time: 3600
    #     update_cache: true
    #   become: true

    # - name: Install packages
    #   apt:
    #     name: "{{ item }}"
    #   loop:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - software-properties-common
    #     - gnupg2
    #   become: true
