---
- hosts: all
  tasks:
    - name: Create Configuration Directories
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        state: directory
      loop: "{{ com.ryezone.node.directories }}"
      become: true

    - name: Create Configuration Files
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: root
        group: root
      loop: "{{ com.ryezone.node.conf_files }}"
      become: true

    # install and configure pre-requisites
    - name: Touch Files
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        mode: 644
      loop:
        - /etc/modules-load.d/crio.conf
        - /etc/sysctl.d/99-kubernetes-cri.conf
      become: true
    - name: crio.conf - Set Values
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/crio.conf
        line: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: yes
    - name: load modules
      community.general.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: true
    - name: 99-kubernetes-cri.conf - Set Values
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        sysctl_set: true
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
      become: true
    - name: addPackage signing Keys
      ansible.builtin.apt_key:
        url: "{{ item.url }}"
        keyring: "{{ item.keyring }}"
        id: "{{ item.key_id }}"
        state: present
      loop:
        - url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ com.ryezone.platform.k8s.cri_o.os }}/Release.key"
          keyring: /etc/apt/trusted.gpg.d/libcontainers.gpg
          key_id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
        - url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ com.ryezone.platform.k8s.cri_o.version }}/{{ com.ryezone.platform.k8s.cri_o.os }}/Release.key"
          keyring: /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg
          key_id: 2472D6D0D2F66AF87ABA8DA34D64390375060AA4
        - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          keyring: /etc/apt/trusted.gpg.d/google_cloud_packages.gpg
          key_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
      become: true
    - name: Add Package Repositories
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.path }}"
        state: present
      loop:
        - path: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable
          repo: "deb [arch=amd64] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ com.ryezone.platform.k8s.cri_o.os }}/ /"
        - path: "/etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ com.ryezone.platform.k8s.cri_o.version }}"
          repo: "deb [arch=amd64] http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ com.ryezone.platform.k8s.cri_o.version }}/{{ com.ryezone.platform.k8s.cri_o.os }}/ /"
        - path: /etc/apt/sources.list.d/kubernetes
          repo: "deb https://apt.kubernetes.io/ kubernetes-{{ com.ryezone.platform.k8s.kubeadm.release }} main"
      become: true
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
    - name: Install Packages
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        - cri-o
        - cri-o-runc
        - kubelet
        - kubeadm
        - kubectl
      become: true
    - name: get apt mark holds
      ansible.builtin.command: apt-mark showhold
      register: holds
      changed_when: false
      become: true
    - name: apt mark packages
      ansible.builtin.command: "apt-mark hold {{item}}"
      loop:
        - cri-o
        - cri-o-runc
        - kubelet
        - kubeadm
        - kubectl
      when: item not in holds.stdout
      become: true
    - name: Create CRI-O Configuration Files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/{{ item }}"
        mode: "644"
        owner: root
        group: root
      loop:
        - etc/crio/crio.conf.d/02-cgroup-manager.conf
      become: true
    - name: Enable CRI-O Daemon
      ansible.builtin.systemd:
        name: crio
        daemon_reload: true
        enabled: true
        state: started
      become: true
