---
- hosts: all
  tasks:
    - name: Create Configuration Directories
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        state: directory
      loop: "{{ com.ryezone.node.directories }}"
      become: true

    - name: Create Configuration Files
      ansible.builtin.template:
        src: "{{ item.template }}"
        dest: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: root
        group: root
      loop: "{{ com.ryezone.node.conf_files }}"
      become: true

    # install and configure pre-requisites
    - name: Touch Files
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
        owner: root
        mode: 644
      loop:
        - /etc/modules-load.d/crio.conf
        - /etc/sysctl.d/99-kubernetes-cri.conf
      become: true
    - name: crio.conf - Set Values
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/crio.conf
        line: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: yes
    - name: load modules
      community.general.modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter
      become: true
    - name: 99-kubernetes-cri.conf - Set Values
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        sysctl_set: true
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
      become: true

    # - name: add Package signing Keys
    #   apt_key:
    #     url: "{{ item }}"
    #     state: present
    #   loop:
    #     - https://download.docker.com/linux/ubuntu/gpg
    #   become: true

    # - name: Add Package Repositories
    #   apt_repository:
    #     repo: "{{ item }}"
    #     state: present
    #   loop:
    #     - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    #   become: true

    # - name: Update Cache
    #   apt:
    #     cache_valid_time: 3600
    #     update_cache: true
    #   become: true

    # - name: Install packages
    #   apt:
    #     name: "{{ item }}"
    #   loop:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - software-properties-common
    #     - gnupg2
    #   become: true
