- hosts: localhost
  tasks:
    - name: show all the hosts matching the pattern, ie all but the group www
      set_fact:
        nodes: "{{ lookup('inventory_hostnames', 'controlplane:*').split(',') }}"
    - debug:
        msg: "{{ item }}"
      loop: "{{ nodes }}"
    - template:
        src: test.yml.j2
        dest: /home/esten/test.yml