---
com:
  ryezone:
    node:
      directories:
        - /etc/modules-load.d
        - /etc/sysctl.d
    platform:
      zone: dev.ryezone.com
      k8s:
        kubeadm:
          release: xenial
        cri_o:
          os: "x{{ ansible_distribution  }}_{{ ansible_distribution_version }}"
          version: "1.20"
        images:
          haproxy: haproxy:2.1.4
          keepalived: osixia/keepalived:1.3.5-1
        kube_api_server:
          hostname: kube_api.dev.ryezone.com
          port: 64443
