---
com:
  ryezone:
    node:
      ip_advertise_address: "{{ ansible_all_ipv4_addresses[0] }}"
    platform:
      environment: dev
      cloudflare:
        api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
        zone: ryezone.com
      keepalived:
        virtual_router_id: 50
        auth_pass: 42
        vip: 10.5.99.20
      k8s:
        cgroup_driver: cgroupfs
        kubeadm:
          release: xenial
        cri_o:
          os: "x{{ ansible_distribution  }}_{{ ansible_distribution_version }}"
          version: "1.20"
        images:
          haproxy: haproxy:2.1.4
          keepalived: osixia/keepalived:1.3.5-1
        kube_api_server:
          port: 64443
