---
com:
  ryezone:
    node:
      directories:
        - /etc/modules-load.d
        - /etc/sysctl.d
      conf_files:
    platform:
      zone: dev.ryezone.com
      k8s:
        images:
          haproxy: haproxy:2.1.4
          keepalived: osixia/keepalived:1.3.5-1
        kube_api_server:
          hostname: kube_api.dev.ryezone.com
          port: 64443
