---
com:
  ryezone:
    platform:
      zone: dev.ryezone.com
      k8s:
        images:
          haproxy: haproxy:2.1.4
          keepalived: osixia/keepalived:1.3.5-1
          
        kube_api_server:
          hostname: kube_api.dev.ryezone.com
          port: 64443
          keepalived:
            state: backup
            interface: eth0
            router_id: 50
            priority: 101
            auth_pass: 42
            vip: 10.5.50.20
          haproxy:
            backend_servers:
              - controlplane01
              - controlplane02
              - controlplane03
            source_port: 6443
