---
com:
  ryezone:
    platform:
      k8s:
        kube_api_server:
          keepalived:
            state: BACKUP
            interface: enp0s8
            router_id: 50
            priority: 101
            auth_pass: 42
            vip: 10.5.99.20
          haproxy:
            backend_servers:
              - controlplane01
              - controlplane02
              - controlplane03
            source_port: 6443
