- name: check join status
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: control_plane_joined

- name: create kubeadm join file
  ansible.builtin.template:
    src: kubeadm.join.controlplane.yml.j2
    dest: /home/{{ ansible_user }}/kubeadm.join.controlplane.yml

- name: run kubeadm join on additional controlplane node
  ansible.builtin.command:
    argv:
      - kubeadm
      - join
      - --config
      - /home/{{ ansible_user }}/kubeadm.join.controlplane.yml
  become: true
  when:
    - not control_plane_joined.stat.exists

- name: Create .kube Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: directory
  when:
    - not control_plane_joined.stat.exists

- name: Copy kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  when:
    - not control_plane_joined.stat.exists
