- name: check join status
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: control_plane_joined

- name: create kubeadm init file
  ansible.builtin.template:
    src: kubeadm.join.controlplane.yml.j2
    dest: /home/{{ ansible_user }}/kubeadm.join.controlplane.yml

- name: set ca certificate hash
  ansible.builtin.set_fact:
    discovery_token_ca_cert_hash: "{{ hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token_ca_cert_hash'].stdout }}"
  when:
    - hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token_ca_cert_hash'] is defined

- name: run kubeadm join on additional controlplane node
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --config
      - /home/{{ ansible_user }}/kubeadm.join.controlplane.yml
  become: true
  when:
    - not control_plane_joined.stat.exists

# - name: Join Additional Controlplane Node
#   ansible.builtin.command:
#     argv:
#       - kubeadm
#       - join
#       - "{{ kubernetes_control_plane_endpoint_address }}:{{ kubernetes_control_plane_endpoint_port }}"
#       - --apiserver-advertise-address
#       - "{{ kubernetes_advertise_address }}"
#       - --certificate-key
#       - "{{ hostvars[kubernetes_initial_controlplane_hostvar_key]['certificate_key'].stdout }}"
#       - --control-plane
#       - --discovery-token
#       - "{{ hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token'].stdout }}"
#       - --discovery-token-ca-cert-hash
#       - "sha256:{{ hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token_ca_cert_hash'].stdout }}"
#   when:
#     - not control_plane_joined.stat.exists
#     - hostvars[kubernetes_initial_controlplane_hostvar_key]['certificate_key'] is defined
#     - hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token'] is defined
#     - hostvars[kubernetes_initial_controlplane_hostvar_key]['discovery_token_ca_cert_hash'] is defined
#   become: true

- name: Create .kube Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: directory
  when:
    - not control_plane_joined.stat.exists

- name: Copy kube config
  ansible.builtin.copy:
    content: "{{ hostvars[kubernetes_initial_controlplane_hostvar_key]['kube_config'].stdout }}"
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when:
    - not control_plane_joined.stat.exists
