- name: check join status
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: control_plane_joined

- name: create kubeadm init file
  ansible.builtin.template:
    src: kubeadm.init.yml.j2
    dest: /home/{{ ansible_user }}/kubeadm.init.yml

- name: run kubeadm init on initial controlplane node
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --config
      - /home/{{ ansible_user }}/kubeadm.init.yml
  become: true
  when:
    - not control_plane_joined.stat.exists

- name: Create .kube Directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: directory
  when:
    - kubernetes_is_initial_controlplane
    - not control_plane_joined.stat.exists

- name: Copy kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
  when:
    - not control_plane_joined.stat.exists

- name: upload cluster certificates
  ansible.builtin.command: kubeadm init phase upload-certs --upload-certs --certificate-key={{ certificate_key }}
  become: true