---
# Initialize Initial Node

- name: run kubeadm init on initial controlplane node
  ansible.builtin.include_tasks:
    file: initial_controlplane.yml
  when:
    - kubernetes_is_initial_controlplane

- name: install cni plugin
  ansible.builtin.include_tasks:
    file: install_calico_cni.yml
  when:
    - kubernetes_is_initial_controlplane

# Join Controlplane Node

- name: join control plane node
  ansible.builtin.include_tasks:
    file: additional_controlplane.yml
  when:
    - not kubernetes_is_initial_controlplane
    - kubernetes_is_controlplane

# Join Worker Node

- name: join worker node
  ansible.builtin.include_tasks:
    file: node.yml
  when:
    - not kubernetes_is_initial_controlplane
    - not kubernetes_is_controlplane
