- name: check join status
  ansible.builtin.stat:
    path: /etc/kubernetes/pki/ca.crt
  register: control_plane_joined

- name: create kubeadm join file
  ansible.builtin.template:
    src: kubeadm.join.node.yml.j2
    dest: /home/{{ ansible_user }}/kubeadm.join.node.yml

- name: run kubeadm init on node
  ansible.builtin.command:
    argv:
      - kubeadm
      - join
      - --config
      - /home/{{ ansible_user }}/kubeadm.join.node.yml
  become: true
  when:
    - not control_plane_joined.stat.exists
